name: Publish website

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: yarn
        
    - name: Setup GIT user
      uses: fregante/setup-git-user@v1

    - run: yarn install
    
    - run: |
        GIT_USER=github-actions[bot] DEPLOYMENT_BRANCH=gh-pages yarn deploy
