name: Publish website

on:
  push:
    branches: [ master ]

jobs:
  deokiy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        
    - run: yarn install
    - run: |
        GIT_USER=${{github.actor}} DEPLOYMENT_BRANCH=gh-pages yarn deploy
